### ISSUE TITLE
Home - Scaletta della giornata/Info Generali

### ISSUE THREAD

**Issue by HarlockOfficial** [hacktoberfest-unicam/hacktoberfest-2023-frontend#1]
Pagina di benvenuto, eg. frase ad effetto e logo #TODO e logo Hacktoberfest
Lista Eventi e Time schedule della giornata
    8:00-9:00 Benvenuto
    9:00 - 9:05 Saluto del Presidente
    XX:YY - ZZ:WW Inizio Hackathon (REPO: link)
Login/Registration
Navbar (Home, Classifica, Profilo personale if logged-in)

Responsive? OPTIONAL

**Comment by AlexDicy** [comment]
Vecchia locandina:
![Image](https://github.com/hacktoberfest-unicam/hacktoberfest-2023-frontend/assets/11839341/d44591bc-3bb8-418b-b90e-404807196eac)
